#!/bin/bash

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.
# See https://gist.github.com/rossf7/664dc1eb02f514993c7215d37058965c and
# https://docs.docker.com/docker-cloud/builds/advanced/

#getting the right arch from the docker tag, which is specified in the automatic build configuration. The working tags are: amd64, armhf, aarch64.
BUILD_ARCH=${DOCKER_TAG}
#here the base image version is specified.
ALPINE_VERSION=3.11
echo "Build hook running"
docker build \
             --file "${DOCKERFILE_PATH}"\
             --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg BUILD_VERSION=$(git describe --tags) \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VCS_URL=$(git config --get remote.origin.url) \
             --build-arg VCS_BRANCH=$(git rev-parse --abbrev-ref HEAD) \
             --build-arg QEMU_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "${BUILD_ARCH::-2}" || echo "${BUILD_ARCH}") \
             --build-arg IMAGE_ARCH=$([ "${BUILD_ARCH}" == "armhf" ] && echo "arm32v7/alpine:${ALPINE_VERSION}" || ([ "${BUILD_ARCH}" == "aarch64" ] && echo "arm64v8/alpine:${ALPINE_VERSION}") || echo "alpine:${ALPINE_VERSION}") \
             --tag "$IMAGE_NAME" \
             .
