#!/bin/bash
echo "Creating multi-arch-manifest.yaml"
cat > multi-arch-manifest.yaml << EOF
image: $(echo "${DOCKER_REPO}" | cut -d/ -f2,3):latest 
manifests:
  - image: $(echo "${DOCKER_REPO}" | cut -d/ -f2,3):amd64
    platform:
      architecture: amd64
      os: linux
  - image: $(echo "${DOCKER_REPO}" | cut -d/ -f2,3):armhf
    platform:
      architecture: arm
      os: linux
  - image: $(echo "${DOCKER_REPO}" | cut -d/ -f2,3):aarch64
    platform:
      architecture: arm64
      os: linux
EOF

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec multi-arch-manifest.yaml
