#!/bin/bash
Echo "Creating multi-arch-manifest.yaml"
cat > multi-arch-manifest.yaml << EOF
image:
${DOCKER_REPO}:latest manifests:
  - image: ${DOCKER_REPO}:amd64
    platform:
      architecture: amd64
      os: linux
  - image: ${DOCKER_REPO}:armhf
    platform:
      architecture: arm
      os: linux
  - image: ${DOCKER_REPO}:aarch64
    platform:
      architecture: arm64
      os: linux
EOF

cat multi-arch-manifest.yaml

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-spec multi-arch-manifest.yaml
