#!/bin/bash
echo Activating experimental features:
export DOCKER_CLI_EXPERIMENTAL=enabled
docker version
docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
