#!/bin/bash
#Getting arch from docker tag instead of docker_path
BUILD_ARCH=$(echo "${DOCKER_TAG}")

[ "${BUILD_ARCH}" == "amd64" ] && \
    { echo 'qemu-user-static: Registration not required for current arch'; exit 0; }

docker run --rm --privileged multiarch/qemu-user-static:register --reset
